// <auto-generated />
using System;
using LibraryBackOffice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryBackOffice.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260401130413_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryBackOffice.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("LibraryBackOffice.Models.HistoriqueAbonnement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date_Expiration")
                        .HasColumnType("date")
                        .HasColumnName("date_expiration");

                    b.Property<DateTime?>("Date_Paiement")
                        .HasColumnType("date")
                        .HasColumnName("date_paiement");

                    b.Property<int>("Id_ModePaiement")
                        .HasColumnType("int")
                        .HasColumnName("id_modepaiement");

                    b.Property<int>("Id_TypeAbonnement")
                        .HasColumnType("int")
                        .HasColumnName("id_typeabonnement");

                    b.Property<int>("Id_Utilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.HasKey("Id");

                    b.HasIndex("Id_ModePaiement");

                    b.HasIndex("Id_TypeAbonnement");

                    b.HasIndex("Id_Utilisateur");

                    b.ToTable("historiqueabonnement", (string)null);
                });

            modelBuilder.Entity("LibraryBackOffice.Models.HistoriqueLecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date_Lecture")
                        .HasColumnType("date")
                        .HasColumnName("date_lecture");

                    b.Property<int>("Id_Livre")
                        .HasColumnType("int")
                        .HasColumnName("id_livre");

                    b.Property<int>("Id_Utilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.HasKey("Id");

                    b.HasIndex("Id_Livre");

                    b.HasIndex("Id_Utilisateur");

                    b.ToTable("historiquelecture", (string)null);
                });

            modelBuilder.Entity("LibraryBackOffice.Models.HistoriquePaiementLivre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date_Lecture")
                        .HasColumnType("date")
                        .HasColumnName("date_lecture");

                    b.Property<int>("Id_Livre")
                        .HasColumnType("int")
                        .HasColumnName("id_livre");

                    b.Property<int>("Id_Utilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.Property<double>("Prix")
                        .HasColumnType("float")
                        .HasColumnName("prix");

                    b.HasKey("Id");

                    b.HasIndex("Id_Livre");

                    b.HasIndex("Id_Utilisateur");

                    b.ToTable("historiquepaiementlivre", (string)null);
                });

            modelBuilder.Entity("LibraryBackOffice.Models.Livre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Auteur")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("auteur");

                    b.Property<DateTime?>("Date_Edition")
                        .HasColumnType("date")
                        .HasColumnName("date_edition");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("document");

                    b.Property<int>("Etat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("etat");

                    b.Property<int>("Id_TypeLivre")
                        .HasColumnType("int")
                        .HasColumnName("id_typelivre");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<string>("Saison")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("saison");

                    b.Property<string>("Sous_Titre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sous_titre");

                    b.Property<string>("Titre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("titre");

                    b.HasKey("Id");

                    b.HasIndex("Id_TypeLivre");

                    b.ToTable("livre", (string)null);
                });

            modelBuilder.Entity("LibraryBackOffice.Models.ModePaiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Mode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mode");

                    b.HasKey("Id");

                    b.ToTable("modePaiement", (string)null);
                });

            modelBuilder.Entity("LibraryBackOffice.Models.TypeAbonnement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type_Abonnement")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("type_abonnement");

                    b.HasKey("Id");

                    b.ToTable("typeAbonnement", (string)null);
                });

            modelBuilder.Entity("LibraryBackOffice.Models.TypeLivre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type_Livre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("type_livre");

                    b.HasKey("Id");

                    b.ToTable("typeLivre", (string)null);
                });

            modelBuilder.Entity("LibraryBackOffice.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateEntree")
                        .HasColumnType("date")
                        .HasColumnName("dateentree");

                    b.Property<int>("Etat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("etat");

                    b.Property<string>("Mail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mail");

                    b.Property<string>("Mdp")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mdp");

                    b.Property<string>("Nom")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("prenom");

                    b.Property<string>("Telephone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("telephone");

                    b.HasKey("Id");

                    b.ToTable("utilisateur", (string)null);
                });

            modelBuilder.Entity("LibraryBackOffice.Models.HistoriqueAbonnement", b =>
                {
                    b.HasOne("LibraryBackOffice.Models.ModePaiement", "ModePaiement")
                        .WithMany("HistoriqueAbonnements")
                        .HasForeignKey("Id_ModePaiement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryBackOffice.Models.TypeAbonnement", "TypeAbonnement")
                        .WithMany("HistoriqueAbonnements")
                        .HasForeignKey("Id_TypeAbonnement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryBackOffice.Models.Utilisateur", "Utilisateur")
                        .WithMany("HistoriqueAbonnements")
                        .HasForeignKey("Id_Utilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModePaiement");

                    b.Navigation("TypeAbonnement");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("LibraryBackOffice.Models.HistoriqueLecture", b =>
                {
                    b.HasOne("LibraryBackOffice.Models.Livre", "Livre")
                        .WithMany("HistoriqueLectures")
                        .HasForeignKey("Id_Livre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryBackOffice.Models.Utilisateur", "Utilisateur")
                        .WithMany("HistoriqueLectures")
                        .HasForeignKey("Id_Utilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livre");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("LibraryBackOffice.Models.HistoriquePaiementLivre", b =>
                {
                    b.HasOne("LibraryBackOffice.Models.Livre", "Livre")
                        .WithMany("HistoriquePaiementLivres")
                        .HasForeignKey("Id_Livre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryBackOffice.Models.Utilisateur", "Utilisateur")
                        .WithMany("HistoriquePaiementLivres")
                        .HasForeignKey("Id_Utilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livre");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("LibraryBackOffice.Models.Livre", b =>
                {
                    b.HasOne("LibraryBackOffice.Models.TypeLivre", "TypeLivre")
                        .WithMany("Livres")
                        .HasForeignKey("Id_TypeLivre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeLivre");
                });

            modelBuilder.Entity("LibraryBackOffice.Models.Livre", b =>
                {
                    b.Navigation("HistoriqueLectures");

                    b.Navigation("HistoriquePaiementLivres");
                });

            modelBuilder.Entity("LibraryBackOffice.Models.ModePaiement", b =>
                {
                    b.Navigation("HistoriqueAbonnements");
                });

            modelBuilder.Entity("LibraryBackOffice.Models.TypeAbonnement", b =>
                {
                    b.Navigation("HistoriqueAbonnements");
                });

            modelBuilder.Entity("LibraryBackOffice.Models.TypeLivre", b =>
                {
                    b.Navigation("Livres");
                });

            modelBuilder.Entity("LibraryBackOffice.Models.Utilisateur", b =>
                {
                    b.Navigation("HistoriqueAbonnements");

                    b.Navigation("HistoriqueLectures");

                    b.Navigation("HistoriquePaiementLivres");
                });
#pragma warning restore 612, 618
        }
    }
}
